"""Update goal model

Revision ID: 51cc901fd6c1
Revises: b8887602ded1
Create Date: 2026-07-23 21:22:41.975981

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "51cc901fd6c1"
down_revision: Union[str, Sequence[str], None] = "b8887602ded1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("goals", sa.Column("target_distance", sa.Float(), nullable=False))
    op.add_column("goals", sa.Column("target_time_minutes", sa.Float(), nullable=False))
    op.add_column("goals", sa.Column("target_date", sa.Date(), nullable=False))
    op.drop_column("goals", "current_value")
    op.drop_column("goals", "target_unit")
    op.drop_column("goals", "status")
    op.drop_column("goals", "target_value")
    op.drop_column("goals", "goal_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "goals",
        sa.Column(
            "goal_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "goals",
        sa.Column(
            "target_value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "goals",
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    op.add_column(
        "goals",
        sa.Column(
            "target_unit", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "goals",
        sa.Column(
            "current_value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("goals", "target_date")
    op.drop_column("goals", "target_time_minutes")
    op.drop_column("goals", "target_distance")
    # ### end Alembic commands ###
