"""add ai coach tables

Revision ID: 9e56c8ff36e4
Revises: ce4c3d50aea3
Create Date: 2026-07-31 16:13:37.012237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e56c8ff36e4'
down_revision: Union[str, Sequence[str], None] = 'ce4c3d50aea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_athlete_id'), 'activities', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_activities_external_id'), 'activities', ['external_id'], unique=False)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_source'), 'activities', ['source'], unique=False)
    op.create_table('athlete_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('sleep_score', sa.Integer(), nullable=False),
    sa.Column('soreness_score', sa.Integer(), nullable=False),
    sa.Column('energy_score', sa.Integer(), nullable=False),
    sa.Column('motivation_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_checkins_athlete_id'), 'athlete_checkins', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_athlete_checkins_id'), 'athlete_checkins', ['id'], unique=False)
    op.create_table('athlete_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('memory_value', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athlete_memories_athlete_id'), 'athlete_memories', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_athlete_memories_id'), 'athlete_memories', ['id'], unique=False)
    op.create_table('coach_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_decisions_athlete_id'), 'coach_decisions', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_coach_decisions_id'), 'coach_decisions', ['id'], unique=False)
    op.create_table('coach_learning_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('confidence_change', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_learning_events_athlete_id'), 'coach_learning_events', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_coach_learning_events_id'), 'coach_learning_events', ['id'], unique=False)
    op.create_table('voice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_message', sa.String(length=1000), nullable=False),
    sa.Column('coach_response', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_sessions_athlete_id'), 'voice_sessions', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_voice_sessions_id'), 'voice_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_voice_sessions_session_id'), 'voice_sessions', ['session_id'], unique=False)
    op.create_table('activity_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('average_pace', sa.Float(), nullable=True),
    sa.Column('average_heart_rate', sa.Integer(), nullable=True),
    sa.Column('max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('cadence', sa.Float(), nullable=True),
    sa.Column('elevation_gain', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('training_load', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_metrics_activity_id'), 'activity_metrics', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_metrics_id'), 'activity_metrics', ['id'], unique=False)
    op.create_table('workout_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_session_id', sa.Integer(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('target_time', sa.String(length=50), nullable=True),
    sa.Column('recovery', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_intervals_id'), 'workout_intervals', ['id'], unique=False)
    op.create_index(op.f('ix_workout_intervals_training_session_id'), 'workout_intervals', ['training_session_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_athlete_id'), 'training_sessions', ['athlete_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_sessions_athlete_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_workout_intervals_training_session_id'), table_name='workout_intervals')
    op.drop_index(op.f('ix_workout_intervals_id'), table_name='workout_intervals')
    op.drop_table('workout_intervals')
    op.drop_index(op.f('ix_activity_metrics_id'), table_name='activity_metrics')
    op.drop_index(op.f('ix_activity_metrics_activity_id'), table_name='activity_metrics')
    op.drop_table('activity_metrics')
    op.drop_index(op.f('ix_voice_sessions_session_id'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_id'), table_name='voice_sessions')
    op.drop_index(op.f('ix_voice_sessions_athlete_id'), table_name='voice_sessions')
    op.drop_table('voice_sessions')
    op.drop_index(op.f('ix_coach_learning_events_id'), table_name='coach_learning_events')
    op.drop_index(op.f('ix_coach_learning_events_athlete_id'), table_name='coach_learning_events')
    op.drop_table('coach_learning_events')
    op.drop_index(op.f('ix_coach_decisions_id'), table_name='coach_decisions')
    op.drop_index(op.f('ix_coach_decisions_athlete_id'), table_name='coach_decisions')
    op.drop_table('coach_decisions')
    op.drop_index(op.f('ix_athlete_memories_id'), table_name='athlete_memories')
    op.drop_index(op.f('ix_athlete_memories_athlete_id'), table_name='athlete_memories')
    op.drop_table('athlete_memories')
    op.drop_index(op.f('ix_athlete_checkins_id'), table_name='athlete_checkins')
    op.drop_index(op.f('ix_athlete_checkins_athlete_id'), table_name='athlete_checkins')
    op.drop_table('athlete_checkins')
    op.drop_index(op.f('ix_activities_source'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_external_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_athlete_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
