"""initial_schema

Revision ID: b8887602ded1
Revises:
Create Date: 2026-07-23 16:50:16.080275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b8887602ded1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "athletes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("preferred_name", sa.String(length=100), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column(
            "sex",
            sa.Enum("MALE", "FEMALE", "OTHER", "PREFER_NOT_TO_SAY", name="sex"),
            nullable=True,
        ),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column(
            "sport",
            sa.Enum(
                "RUNNING",
                "CYCLING",
                "TRIATHLON",
                "SWIMMING",
                "ROWING",
                "STRENGTH",
                "CROSSFIT",
                "HYROX",
                "OTHER",
                name="sport",
            ),
            nullable=True,
        ),
        sa.Column("primary_event", sa.String(length=100), nullable=True),
        sa.Column(
            "experience_level",
            sa.Enum(
                "BEGINNER",
                "NOVICE",
                "INTERMEDIATE",
                "ADVANCED",
                "ELITE",
                "PROFESSIONAL",
                name="experiencelevel",
            ),
            nullable=True,
        ),
        sa.Column("years_training", sa.Integer(), nullable=True),
        sa.Column("weekly_training_days", sa.Integer(), nullable=True),
        sa.Column("weekly_training_hours", sa.Float(), nullable=True),
        sa.Column("weekly_distance", sa.Float(), nullable=True),
        sa.Column("resting_hr", sa.Integer(), nullable=True),
        sa.Column("threshold_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("ftp", sa.Integer(), nullable=True),
        sa.Column("vo2_max", sa.Float(), nullable=True),
        sa.Column(
            "injury_status",
            sa.Enum("HEALTHY", "MINOR", "RECOVERING", "INJURED", name="injurystatus"),
            nullable=True,
        ),
        sa.Column("coach_notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_athletes_id"), "athletes", ["id"], unique=False)
    op.create_index(op.f("ix_athletes_user_id"), "athletes", ["user_id"], unique=False)
    op.create_table(
        "goals",
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("goal_type", sa.String(length=50), nullable=False),
        sa.Column("target_value", sa.Float(), nullable=False),
        sa.Column("target_unit", sa.String(length=20), nullable=False),
        sa.Column("current_value", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goals_athlete_id"), "goals", ["athlete_id"], unique=False)
    op.create_index(op.f("ix_goals_id"), "goals", ["id"], unique=False)
    op.create_table(
        "training_sessions",
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("session_type", sa.String(length=100), nullable=False),
        sa.Column("distance", sa.Float(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("average_pace", sa.Float(), nullable=False),
        sa.Column("average_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("cadence", sa.Integer(), nullable=True),
        sa.Column("elevation_gain", sa.Float(), nullable=True),
        sa.Column("training_load", sa.Float(), nullable=True),
        sa.Column("rpe", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_sessions_athlete_id"),
        "training_sessions",
        ["athlete_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_training_sessions_id"), "training_sessions", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_training_sessions_id"), table_name="training_sessions")
    op.drop_index(
        op.f("ix_training_sessions_athlete_id"), table_name="training_sessions"
    )
    op.drop_table("training_sessions")
    op.drop_index(op.f("ix_goals_id"), table_name="goals")
    op.drop_index(op.f("ix_goals_athlete_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_athletes_user_id"), table_name="athletes")
    op.drop_index(op.f("ix_athletes_id"), table_name="athletes")
    op.drop_table("athletes")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
