"""initial schema

Revision ID: ce4c3d50aea3
Revises:
Create Date: 2026-07-27 11:59:18.884062

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce4c3d50aea3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "athletes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("height_cm", sa.Float(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column("resting_hr", sa.Integer(), nullable=False),
        sa.Column("max_hr", sa.Integer(), nullable=False),
        sa.Column("sport", sa.String(length=50), nullable=False),
        sa.Column("primary_event", sa.String(length=50), nullable=False),
        sa.Column("experience_level", sa.String(length=50), nullable=True),
        sa.Column("weekly_distance", sa.Float(), nullable=True),
        sa.Column("training_days_per_week", sa.Integer(), nullable=True),
        sa.Column("current_5k_time", sa.Float(), nullable=True),
        sa.Column("injury_status", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_sessions_id"),
        "training_sessions",
        ["id"],
        unique=False,
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("goal_type", sa.String(length=50), nullable=False),
        sa.Column("target_value", sa.Float(), nullable=False),
        sa.Column("target_unit", sa.String(length=20), nullable=False),
        sa.Column("current_value", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_goals_athlete_id"), "goals", ["athlete_id"], unique=False)
    op.create_index(op.f("ix_goals_id"), "goals", ["id"], unique=False)
    op.create_table(
        "training_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("session_type", sa.String(), nullable=False),
        sa.Column("distance", sa.Float(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("average_pace", sa.Float(), nullable=False),
        sa.Column("average_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("cadence", sa.Integer(), nullable=True),
        sa.Column("elevation_gain", sa.Float(), nullable=True),
        sa.Column("training_load", sa.Float(), nullable=True),
        sa.Column("rpe", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athletes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_sessions_id"),
        "training_sessions",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_training_sessions_id"), table_name="training_sessions")
    op.drop_table("training_sessions")
    op.drop_index(op.f("ix_goals_id"), table_name="goals")
    op.drop_index(op.f("ix_goals_athlete_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_athletes_id"), table_name="athletes")
    op.drop_table("athletes")
    # ### end Alembic commands ###
