"""create performance cycles

Revision ID: d5ee7c670cb3
Revises: c5d87d28e53e
Create Date: 2026-07-24 17:21:08.996203

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d5ee7c670cb3"
down_revision: Union[str, Sequence[str], None] = "c5d87d28e53e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "performance_cycles",
        "status",
        existing_type=postgresql.ENUM(
            "PLANNED", "ACTIVE", "COMPLETED", "CANCELLED", name="performancecyclestatus"
        ),
        type_=sa.Enum(
            "PLANNED",
            "ACTIVE",
            "COMPLETED",
            "CANCELLED",
            name="performance_cycle_status",
        ),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_performance_cycles_athlete_id"),
        "performance_cycles",
        ["athlete_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_performance_cycles_athlete_id"), table_name="performance_cycles"
    )
    op.alter_column(
        "performance_cycles",
        "status",
        existing_type=sa.Enum(
            "PLANNED",
            "ACTIVE",
            "COMPLETED",
            "CANCELLED",
            name="performance_cycle_status",
        ),
        type_=postgresql.ENUM(
            "PLANNED", "ACTIVE", "COMPLETED", "CANCELLED", name="performancecyclestatus"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
